apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: testing-app-ingress-service
  namespace: {{ .Values.toolingnamespace }}
  labels:
    name: testing-app-ingress-service
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.vaultappbaseURL }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ .Values.vaultservice }}
            port:
              number: 80
