apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.vaultservice }}
  namespace: {{ .Values.toolingnamespace }}
spec:
  selector:
    app: {{ .Values.vaultApplicationName }}
  ports:
  - port: 80
    targetPort: 8200
  
  type: ClusterIP
